-- TABLA DE AUDITORÍA (sin cambios)
DROP TABLE AUDITORIA_OPERACIONES;

CREATE TABLE AUDITORIA_OPERACIONES (
    ID_AUDIT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA      VARCHAR2(50),
    OPERACION  VARCHAR2(10),
    USUARIO    VARCHAR2(30),
    FECHA      DATE,
    INFO       VARCHAR2(4000)
);

-- TIENDA
CREATE OR REPLACE TRIGGER trg_audit_TIENDA
AFTER INSERT OR UPDATE OR DELETE ON TIENDA
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'ID_TIENDA=' || :NEW.ID_TIENDA;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('TIENDA', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'ID_TIENDA=' || :NEW.ID_TIENDA;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('TIENDA', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'ID_TIENDA=' || :OLD.ID_TIENDA;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('TIENDA', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- INVENTARIO
CREATE OR REPLACE TRIGGER trg_audit_INVENTARIO
AFTER INSERT OR UPDATE OR DELETE ON INVENTARIO
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'INVENTARIO_ID=' || :NEW.INVENTARIO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('INVENTARIO', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'INVENTARIO_ID=' || :NEW.INVENTARIO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('INVENTARIO', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'INVENTARIO_ID=' || :OLD.INVENTARIO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('INVENTARIO', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- VENTAS
CREATE OR REPLACE TRIGGER trg_audit_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON VENTAS
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'VENTA_ID=' || :NEW.VENTA_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('VENTAS', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'VENTA_ID=' || :NEW.VENTA_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('VENTAS', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'VENTA_ID=' || :OLD.VENTA_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('VENTAS', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- DETALLE_VENTA (clave compuesta)
CREATE OR REPLACE TRIGGER trg_audit_DETALLE_VENTA
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_VENTA
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'VENTA_ID=' || :NEW.VENTA_ID || ', DETALLE_ID=' || :NEW.DETALLE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('DETALLE_VENTA', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'VENTA_ID=' || :NEW.VENTA_ID || ', DETALLE_ID=' || :NEW.DETALLE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('DETALLE_VENTA', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'VENTA_ID=' || :OLD.VENTA_ID || ', DETALLE_ID=' || :OLD.DETALLE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('DETALLE_VENTA', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- PRODUCTO
CREATE OR REPLACE TRIGGER trg_audit_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'PRODUCTO_ID=' || :NEW.PRODUCTO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PRODUCTO', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'PRODUCTO_ID=' || :NEW.PRODUCTO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PRODUCTO', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'PRODUCTO_ID=' || :OLD.PRODUCTO_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PRODUCTO', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- PROVEEDOR
CREATE OR REPLACE TRIGGER trg_audit_PROVEEDOR
AFTER INSERT OR UPDATE OR DELETE ON PROVEEDOR
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'PROVEEDOR_ID=' || :NEW.PROVEEDOR_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PROVEEDOR', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'PROVEEDOR_ID=' || :NEW.PROVEEDOR_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PROVEEDOR', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'PROVEEDOR_ID=' || :OLD.PROVEEDOR_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('PROVEEDOR', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/

-- CLIENTE
CREATE OR REPLACE TRIGGER trg_audit_CLIENTE
AFTER INSERT OR UPDATE OR DELETE ON CLIENTE
FOR EACH ROW
DECLARE
    v_info VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_info := 'CLIENTE_ID=' || :NEW.CLIENTE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('CLIENTE', 'INSERT', USER, SYSDATE, v_info);
    ELSIF UPDATING THEN
        v_info := 'CLIENTE_ID=' || :NEW.CLIENTE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('CLIENTE', 'UPDATE', USER, SYSDATE, v_info);
    ELSIF DELETING THEN
        v_info := 'CLIENTE_ID=' || :OLD.CLIENTE_ID;
        INSERT INTO AUDITORIA_OPERACIONES (TABLA, OPERACION, USUARIO, FECHA, INFO)
        VALUES ('CLIENTE', 'DELETE', USER, SYSDATE, v_info);
    END IF;
END;
/
