-- En master y remoto crear la tabla de auditoria
DROP TABLE AUDITORIA;
CREATE TABLE AUDITORIA (
    ID_AUDITORIA     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO          VARCHAR2(30),
    FECHA_HORA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPERACION        VARCHAR2(10),  -- INSERT, UPDATE, DELETE
    NOMBRE_TABLA     VARCHAR2(30),
    DETALLE          CLOB
);


-- TRIGGERS PARA MASTER
-- PRODUCTO
CREATE OR REPLACE TRIGGER TRG_AUDIT_PRODUCTO_INS
AFTER INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'PRODUCTO',
          'ID: ' || :NEW.PRODUCTO_ID || ', Nombre: ' || :NEW.NOMBRE || ', Precio: ' || :NEW.PRECIO);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_PRODUCTO_UPD
AFTER UPDATE ON PRODUCTO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'PRODUCTO',
          'ID: ' || :OLD.PRODUCTO_ID || ', Precio: ' || :OLD.PRECIO || ' -> ' || :NEW.PRECIO);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_PRODUCTO_DEL
AFTER DELETE ON PRODUCTO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'PRODUCTO',
          'ID: ' || :OLD.PRODUCTO_ID || ', Nombre: ' || :OLD.NOMBRE);
END;
/

-- CLIENTE
CREATE OR REPLACE TRIGGER TRG_AUDIT_CLIENTE_INS
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'CLIENTE',
          'ID: ' || :NEW.CLIENTE_ID || ', Nombre: ' || :NEW.NOMBRE || ' ' || :NEW.APELLIDO);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_CLIENTE_UPD
AFTER UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'CLIENTE',
          'ID: ' || :OLD.CLIENTE_ID || ', Email: ' || :OLD.EMAIL || ' -> ' || :NEW.EMAIL);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_CLIENTE_DEL
AFTER DELETE ON CLIENTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'CLIENTE',
          'ID: ' || :OLD.CLIENTE_ID || ', Nombre: ' || :OLD.NOMBRE || ' ' || :OLD.APELLIDO);
END;
/

-- PROVEEDOR
CREATE OR REPLACE TRIGGER TRG_AUDIT_PROVEEDOR_INS
AFTER INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'PROVEEDOR',
          'ID: ' || :NEW.PROVEEDOR_ID || ', Nombre: ' || :NEW.NOMBRE);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_PROVEEDOR_UPD
AFTER UPDATE ON PROVEEDOR
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'PROVEEDOR',
          'ID: ' || :OLD.PROVEEDOR_ID || ', Teléfono: ' || :OLD.TELEFONO || ' -> ' || :NEW.TELEFONO);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_PROVEEDOR_DEL
AFTER DELETE ON PROVEEDOR
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'PROVEEDOR',
          'ID: ' || :OLD.PROVEEDOR_ID || ', Nombre: ' || :OLD.NOMBRE);
END;
/

-- TABLA TIENDA FRAGMENTADA
CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_INS
AFTER INSERT ON TIENDA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'TIENDA',
          'ID: ' || :NEW.ID_TIENDA || ', Nombre: ' || :NEW.NOMBRE || ', Región: ' || :NEW.REGION_ID);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_UPD
AFTER UPDATE ON TIENDA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'TIENDA',
          'ID: ' || :OLD.ID_TIENDA || ', Dirección: ' || :OLD.DIRECCION || ' -> ' || :NEW.DIRECCION);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_DEL
AFTER DELETE ON TIENDA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'TIENDA',
          'ID: ' || :OLD.ID_TIENDA || ', Nombre: ' || :OLD.NOMBRE);
END;
/


-- TABLA INVENTARIO FRAGMENTADA
CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_INS
AFTER INSERT ON INVENTARIO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'INVENTARIO',
          'ID: ' || :NEW.INVENTARIO_ID || ', Cantidad: ' || :NEW.CANTIDAD || ', Tienda: ' || :NEW.ID_TIENDA);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_UPD
AFTER UPDATE ON INVENTARIO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'INVENTARIO',
          'ID: ' || :OLD.INVENTARIO_ID || ', Cantidad: ' || :OLD.CANTIDAD || ' -> ' || :NEW.CANTIDAD);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_DEL
AFTER DELETE ON INVENTARIO
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'INVENTARIO',
          'ID: ' || :OLD.INVENTARIO_ID);
END;
/

-- TABLA VENTAS FRAGMENTADA
CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_INS
AFTER INSERT ON VENTAS
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'VENTAS',
          'ID: ' || :NEW.VENTA_ID || ', Cliente: ' || :NEW.CLIENTE_ID || ', Total: ' || :NEW.TOTAL);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_UPD
AFTER UPDATE ON VENTAS
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'VENTAS',
          'ID: ' || :OLD.VENTA_ID || ', Total: ' || :OLD.TOTAL || ' -> ' || :NEW.TOTAL);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_DEL
AFTER DELETE ON VENTAS
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'VENTAS',
          'ID: ' || :OLD.VENTA_ID || ', Cliente: ' || :OLD.CLIENTE_ID);
END;
/
