-- En master y remoto crear la tabla de auditoria
DROP TABLE AUDITORIA;
CREATE TABLE AUDITORIA (
    ID_AUDITORIA     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO          VARCHAR2(30),
    FECHA_HORA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPERACION        VARCHAR2(10),  -- INSERT, UPDATE, DELETE
    NOMBRE_TABLA     VARCHAR2(30),
    DETALLE          CLOB
);


-- TRIGGERS PARA LA BASE DE DATOS REMOTA 
-- TIENDA_NORTE
CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_NORTE_INS
AFTER INSERT ON TIENDA_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'TIENDA_NORTE',
          'ID: ' || :NEW.ID_TIENDA || ', Nombre: ' || :NEW.NOMBRE || ', Región: ' || :NEW.REGION_ID);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_NORTE_UPD
AFTER UPDATE ON TIENDA_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'TIENDA_NORTE',
          'ID: ' || :OLD.ID_TIENDA || ', Dirección: ' || :OLD.DIRECCION || ' -> ' || :NEW.DIRECCION);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_TIENDA_NORTE_DEL
AFTER DELETE ON TIENDA_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'TIENDA_NORTE',
          'ID: ' || :OLD.ID_TIENDA || ', Nombre: ' || :OLD.NOMBRE);
END;
/

-- INVENTARIO_NORTE
CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_NORTE_INS
AFTER INSERT ON INVENTARIO_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'INVENTARIO_NORTE',
          'ID: ' || :NEW.INVENTARIO_ID || ', Cantidad: ' || :NEW.CANTIDAD || ', Tienda: ' || :NEW.ID_TIENDA);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_NORTE_UPD
AFTER UPDATE ON INVENTARIO_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'INVENTARIO_NORTE',
          'ID: ' || :OLD.INVENTARIO_ID || ', Cantidad: ' || :OLD.CANTIDAD || ' -> ' || :NEW.CANTIDAD);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_INVENTARIO_NORTE_DEL
AFTER DELETE ON INVENTARIO_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'INVENTARIO_NORTE',
          'ID: ' || :OLD.INVENTARIO_ID);
END;
/

-- VENTAS_NORTE
CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_NORTE_INS
AFTER INSERT ON VENTAS_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'INSERT', 'VENTAS_NORTE',
          'ID: ' || :NEW.VENTA_ID || ', Cliente: ' || :NEW.CLIENTE_ID || ', Total: ' || :NEW.TOTAL);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_NORTE_UPD
AFTER UPDATE ON VENTAS_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'UPDATE', 'VENTAS_NORTE',
          'ID: ' || :OLD.VENTA_ID || ', Total: ' || :OLD.TOTAL || ' -> ' || :NEW.TOTAL);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_VENTAS_NORTE_DEL
AFTER DELETE ON VENTAS_NORTE
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA (USUARIO, OPERACION, NOMBRE_TABLA, DETALLE)
  VALUES (USER, 'DELETE', 'VENTAS_NORTE',
          'ID: ' || :OLD.VENTA_ID || ', Cliente: ' || :OLD.CLIENTE_ID);
END;
/

-- Probar: SELECT * FROM AUDITORIA ORDER BY FECHA_HORA DESC;
