-- ==============================================
-- SCRIPT CORREGIDO: Fragmentación horizontal - NODO 2
-- PROVINCIAS: Guayas (4), Manabí (5), Esmeraldas (6)
-- TABLAS: PROVINCIA, TIENDA, INVENTARIO, CLIENTE, VENTAS, DETALLE_VENTA
-- ==============================================

-- =====================
-- 1. PROVINCIA
-- =====================
CREATE TABLE PROVINCIA_GUAYAS     AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 4;
CREATE TABLE PROVINCIA_MANABI     AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 5;
CREATE TABLE PROVINCIA_ESMERALDAS AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 6;

ALTER TABLE PROVINCIA_GUAYAS     ADD CONSTRAINT PK_PROV_GUA PRIMARY KEY (PROVINCIA_ID);
ALTER TABLE PROVINCIA_MANABI     ADD CONSTRAINT PK_PROV_MAN PRIMARY KEY (PROVINCIA_ID);
ALTER TABLE PROVINCIA_ESMERALDAS ADD CONSTRAINT PK_PROV_ESM PRIMARY KEY (PROVINCIA_ID);

ALTER TABLE PROVINCIA_GUAYAS     ADD CONSTRAINT CK_PROV_GUA CHECK (PROVINCIA_ID = 4);
ALTER TABLE PROVINCIA_MANABI     ADD CONSTRAINT CK_PROV_MAN CHECK (PROVINCIA_ID = 5);
ALTER TABLE PROVINCIA_ESMERALDAS ADD CONSTRAINT CK_PROV_ESM CHECK (PROVINCIA_ID = 6);

-- =====================
-- 2. TIENDA
-- =====================
CREATE TABLE TIENDA_GUAYAS     AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 4;
CREATE TABLE TIENDA_MANABI     AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 5;
CREATE TABLE TIENDA_ESMERALDAS AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 6;

ALTER TABLE TIENDA_GUAYAS     ADD CONSTRAINT PK_TIENDA_GUA PRIMARY KEY (ID_TIENDA);
ALTER TABLE TIENDA_MANABI     ADD CONSTRAINT PK_TIENDA_MAN PRIMARY KEY (ID_TIENDA);
ALTER TABLE TIENDA_ESMERALDAS ADD CONSTRAINT PK_TIENDA_ESM PRIMARY KEY (ID_TIENDA);

ALTER TABLE TIENDA_GUAYAS ADD CONSTRAINT FK_TIENDA_PROV_GUA FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_GUAYAS (PROVINCIA_ID);
ALTER TABLE TIENDA_MANABI ADD CONSTRAINT FK_TIENDA_PROV_MAN FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_MANABI (PROVINCIA_ID);
ALTER TABLE TIENDA_ESMERALDAS ADD CONSTRAINT FK_TIENDA_PROV_ESM FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_ESMERALDAS (PROVINCIA_ID);

-- =====================
-- 3. INVENTARIO
-- =====================
CREATE TABLE INVENTARIO_GUAYAS AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 4);

CREATE TABLE INVENTARIO_MANABI AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 5);

CREATE TABLE INVENTARIO_ESMERALDAS AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 6);

ALTER TABLE INVENTARIO_GUAYAS ADD CONSTRAINT PK_INV_GUA PRIMARY KEY (INVENTARIO_ID);
ALTER TABLE INVENTARIO_MANABI ADD CONSTRAINT PK_INV_MAN PRIMARY KEY (INVENTARIO_ID);
ALTER TABLE INVENTARIO_ESMERALDAS ADD CONSTRAINT PK_INV_ESM PRIMARY KEY (INVENTARIO_ID);

ALTER TABLE INVENTARIO_GUAYAS ADD CONSTRAINT FK_INV_TIENDA_GUA FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_GUAYAS (ID_TIENDA);
ALTER TABLE INVENTARIO_MANABI ADD CONSTRAINT FK_INV_TIENDA_MAN FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_MANABI (ID_TIENDA);
ALTER TABLE INVENTARIO_ESMERALDAS ADD CONSTRAINT FK_INV_TIENDA_ESM FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_ESMERALDAS (ID_TIENDA);

-- =====================
-- 4. CLIENTE
-- =====================
CREATE TABLE CLIENTE_GUAYAS     AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 4;
CREATE TABLE CLIENTE_MANABI     AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 5;
CREATE TABLE CLIENTE_ESMERALDAS AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 6;

ALTER TABLE CLIENTE_GUAYAS     ADD CONSTRAINT PK_CLI_GUA PRIMARY KEY (CLIENTE_ID);
ALTER TABLE CLIENTE_MANABI     ADD CONSTRAINT PK_CLI_MAN PRIMARY KEY (CLIENTE_ID);
ALTER TABLE CLIENTE_ESMERALDAS ADD CONSTRAINT PK_CLI_ESM PRIMARY KEY (CLIENTE_ID);

ALTER TABLE CLIENTE_GUAYAS ADD CONSTRAINT FK_CLI_PROV_GUA FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_GUAYAS (PROVINCIA_ID);
ALTER TABLE CLIENTE_MANABI ADD CONSTRAINT FK_CLI_PROV_MAN FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_MANABI (PROVINCIA_ID);
ALTER TABLE CLIENTE_ESMERALDAS ADD CONSTRAINT FK_CLI_PROV_ESM FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_ESMERALDAS (PROVINCIA_ID);

-- =====================
-- 5. VENTAS
-- =====================
CREATE TABLE VENTAS_GUAYAS AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 4);

CREATE TABLE VENTAS_MANABI AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 5);

CREATE TABLE VENTAS_ESMERALDAS AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 6);

ALTER TABLE VENTAS_GUAYAS     ADD CONSTRAINT PK_VTA_GUA PRIMARY KEY (VENTA_ID);
ALTER TABLE VENTAS_MANABI     ADD CONSTRAINT PK_VTA_MAN PRIMARY KEY (VENTA_ID);
ALTER TABLE VENTAS_ESMERALDAS ADD CONSTRAINT PK_VTA_ESM PRIMARY KEY (VENTA_ID);

ALTER TABLE VENTAS_GUAYAS ADD CONSTRAINT FK_VTA_CLI_GUA FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_GUAYAS (CLIENTE_ID);
ALTER TABLE VENTAS_MANABI ADD CONSTRAINT FK_VTA_CLI_MAN FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_MANABI (CLIENTE_ID);
ALTER TABLE VENTAS_ESMERALDAS ADD CONSTRAINT FK_VTA_CLI_ESM FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_ESMERALDAS (CLIENTE_ID);

-- =====================
-- 6. DETALLE_VENTA
-- =====================
CREATE TABLE DETALLE_VENTA_GUAYAS AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 4));

CREATE TABLE DETALLE_VENTA_MANABI AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 5));

CREATE TABLE DETALLE_VENTA_ESMERALDAS AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 6));

ALTER TABLE DETALLE_VENTA_GUAYAS     ADD CONSTRAINT PK_DV_GUA PRIMARY KEY (DETALLE_ID);
ALTER TABLE DETALLE_VENTA_MANABI     ADD CONSTRAINT PK_DV_MAN PRIMARY KEY (DETALLE_ID);
ALTER TABLE DETALLE_VENTA_ESMERALDAS ADD CONSTRAINT PK_DV_ESM PRIMARY KEY (DETALLE_ID);

ALTER TABLE DETALLE_VENTA_GUAYAS ADD CONSTRAINT FK_DV_VTA_GUA FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_GUAYAS (VENTA_ID);
ALTER TABLE DETALLE_VENTA_MANABI ADD CONSTRAINT FK_DV_VTA_MAN FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_MANABI (VENTA_ID);
ALTER TABLE DETALLE_VENTA_ESMERALDAS ADD CONSTRAINT FK_DV_VTA_ESM FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_ESMERALDAS (VENTA_ID);

-- ==============================================
-- Fin del script de fragmentación NODO 2
-- ==============================================
