-- ==============================================
-- SCRIPT CORREGIDO: Fragmentación horizontal - NODO 1
-- PROVINCIAS: Pichincha (1), Cotopaxi (2), Tungurahua (3)
-- TABLAS: PROVINCIA, TIENDA, INVENTARIO, CLIENTE, VENTAS, DETALLE_VENTA
-- ==============================================

-- =====================
-- 1. PROVINCIA
-- =====================
CREATE TABLE PROVINCIA_PICHINCHA AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 1;
CREATE TABLE PROVINCIA_COTOPAXI   AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 2;
CREATE TABLE PROVINCIA_TUNGURAHUA AS SELECT * FROM PROVINCIA WHERE PROVINCIA_ID = 3;

ALTER TABLE PROVINCIA_PICHINCHA ADD CONSTRAINT PK_PROV_PICH PRIMARY KEY (PROVINCIA_ID);
ALTER TABLE PROVINCIA_COTOPAXI   ADD CONSTRAINT PK_PROV_COTO PRIMARY KEY (PROVINCIA_ID);
ALTER TABLE PROVINCIA_TUNGURAHUA ADD CONSTRAINT PK_PROV_TUNG PRIMARY KEY (PROVINCIA_ID);

ALTER TABLE PROVINCIA_PICHINCHA ADD CONSTRAINT CK_PROV_PICH CHECK (PROVINCIA_ID = 1);
ALTER TABLE PROVINCIA_COTOPAXI   ADD CONSTRAINT CK_PROV_COTO CHECK (PROVINCIA_ID = 2);
ALTER TABLE PROVINCIA_TUNGURAHUA ADD CONSTRAINT CK_PROV_TUNG CHECK (PROVINCIA_ID = 3);

-- =====================
-- 2. TIENDA
-- =====================
CREATE TABLE TIENDA_PICHINCHA AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 1;
CREATE TABLE TIENDA_COTOPAXI   AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 2;
CREATE TABLE TIENDA_TUNGURAHUA AS SELECT * FROM TIENDA WHERE PROVINCIA_ID = 3;

ALTER TABLE TIENDA_PICHINCHA ADD CONSTRAINT PK_TIENDA_PICH PRIMARY KEY (ID_TIENDA);
ALTER TABLE TIENDA_COTOPAXI   ADD CONSTRAINT PK_TIENDA_COTO PRIMARY KEY (ID_TIENDA);
ALTER TABLE TIENDA_TUNGURAHUA ADD CONSTRAINT PK_TIENDA_TUNG PRIMARY KEY (ID_TIENDA);

ALTER TABLE TIENDA_PICHINCHA ADD CONSTRAINT FK_TIENDA_PROV_PICH FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_PICHINCHA (PROVINCIA_ID);
ALTER TABLE TIENDA_COTOPAXI ADD CONSTRAINT FK_TIENDA_PROV_COTO FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_COTOPAXI (PROVINCIA_ID);
ALTER TABLE TIENDA_TUNGURAHUA ADD CONSTRAINT FK_TIENDA_PROV_TUNG FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_TUNGURAHUA (PROVINCIA_ID);

-- =====================
-- 3. INVENTARIO
-- =====================
CREATE TABLE INVENTARIO_PICHINCHA AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 1);

CREATE TABLE INVENTARIO_COTOPAXI AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 2);

CREATE TABLE INVENTARIO_TUNGURAHUA AS 
SELECT * FROM INVENTARIO 
WHERE ID_TIENDA IN (SELECT ID_TIENDA FROM TIENDA WHERE PROVINCIA_ID = 3);

ALTER TABLE INVENTARIO_PICHINCHA ADD CONSTRAINT PK_INV_PICH PRIMARY KEY (INVENTARIO_ID);
ALTER TABLE INVENTARIO_COTOPAXI   ADD CONSTRAINT PK_INV_COTO PRIMARY KEY (INVENTARIO_ID);
ALTER TABLE INVENTARIO_TUNGURAHUA ADD CONSTRAINT PK_INV_TUNG PRIMARY KEY (INVENTARIO_ID);

ALTER TABLE INVENTARIO_PICHINCHA ADD CONSTRAINT FK_INV_TIENDA_PICH FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_PICHINCHA (ID_TIENDA);
ALTER TABLE INVENTARIO_COTOPAXI ADD CONSTRAINT FK_INV_TIENDA_COTO FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_COTOPAXI (ID_TIENDA);
ALTER TABLE INVENTARIO_TUNGURAHUA ADD CONSTRAINT FK_INV_TIENDA_TUNG FOREIGN KEY (ID_TIENDA)
  REFERENCES TIENDA_TUNGURAHUA (ID_TIENDA);

-- =====================
-- 4. CLIENTE
-- =====================
CREATE TABLE CLIENTE_PICHINCHA AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 1;
CREATE TABLE CLIENTE_COTOPAXI   AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 2;
CREATE TABLE CLIENTE_TUNGURAHUA AS SELECT * FROM CLIENTE WHERE PROVINCIA_ID = 3;

ALTER TABLE CLIENTE_PICHINCHA ADD CONSTRAINT PK_CLI_PICH PRIMARY KEY (CLIENTE_ID);
ALTER TABLE CLIENTE_COTOPAXI   ADD CONSTRAINT PK_CLI_COTO PRIMARY KEY (CLIENTE_ID);
ALTER TABLE CLIENTE_TUNGURAHUA ADD CONSTRAINT PK_CLI_TUNG PRIMARY KEY (CLIENTE_ID);

ALTER TABLE CLIENTE_PICHINCHA ADD CONSTRAINT FK_CLI_PROV_PICH FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_PICHINCHA (PROVINCIA_ID);
ALTER TABLE CLIENTE_COTOPAXI ADD CONSTRAINT FK_CLI_PROV_COTO FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_COTOPAXI (PROVINCIA_ID);
ALTER TABLE CLIENTE_TUNGURAHUA ADD CONSTRAINT FK_CLI_PROV_TUNG FOREIGN KEY (PROVINCIA_ID)
  REFERENCES PROVINCIA_TUNGURAHUA (PROVINCIA_ID);

-- =====================
-- 5. VENTAS
-- =====================
CREATE TABLE VENTAS_PICHINCHA AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 1);

CREATE TABLE VENTAS_COTOPAXI AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 2);

CREATE TABLE VENTAS_TUNGURAHUA AS 
SELECT * FROM VENTAS 
WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 3);

ALTER TABLE VENTAS_PICHINCHA ADD CONSTRAINT PK_VTA_PICH PRIMARY KEY (VENTA_ID);
ALTER TABLE VENTAS_COTOPAXI   ADD CONSTRAINT PK_VTA_COTO PRIMARY KEY (VENTA_ID);
ALTER TABLE VENTAS_TUNGURAHUA ADD CONSTRAINT PK_VTA_TUNG PRIMARY KEY (VENTA_ID);

ALTER TABLE VENTAS_PICHINCHA ADD CONSTRAINT FK_VTA_CLI_PICH FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_PICHINCHA (CLIENTE_ID);
ALTER TABLE VENTAS_COTOPAXI ADD CONSTRAINT FK_VTA_CLI_COTO FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_COTOPAXI (CLIENTE_ID);
ALTER TABLE VENTAS_TUNGURAHUA ADD CONSTRAINT FK_VTA_CLI_TUNG FOREIGN KEY (CLIENTE_ID)
  REFERENCES CLIENTE_TUNGURAHUA (CLIENTE_ID);

-- =====================
-- 6. DETALLE_VENTA
-- =====================
CREATE TABLE DETALLE_VENTA_PICHINCHA AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 1));

CREATE TABLE DETALLE_VENTA_COTOPAXI AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 2));

CREATE TABLE DETALLE_VENTA_TUNGURAHUA AS 
SELECT * FROM DETALLE_VENTA 
WHERE VENTA_ID IN (SELECT VENTA_ID FROM VENTAS WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM CLIENTE WHERE PROVINCIA_ID = 3));

ALTER TABLE DETALLE_VENTA_PICHINCHA ADD CONSTRAINT PK_DV_PICH PRIMARY KEY (DETALLE_ID);
ALTER TABLE DETALLE_VENTA_COTOPAXI   ADD CONSTRAINT PK_DV_COTO PRIMARY KEY (DETALLE_ID);
ALTER TABLE DETALLE_VENTA_TUNGURAHUA ADD CONSTRAINT PK_DV_TUNG PRIMARY KEY (DETALLE_ID);

ALTER TABLE DETALLE_VENTA_PICHINCHA ADD CONSTRAINT FK_DV_VTA_PICH FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_PICHINCHA (VENTA_ID);
ALTER TABLE DETALLE_VENTA_COTOPAXI ADD CONSTRAINT FK_DV_VTA_COTO FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_COTOPAXI (VENTA_ID);
ALTER TABLE DETALLE_VENTA_TUNGURAHUA ADD CONSTRAINT FK_DV_VTA_TUNG FOREIGN KEY (VENTA_ID)
  REFERENCES VENTAS_TUNGURAHUA (VENTA_ID);

-- ==============================================
-- Fin del script de fragmentación NODO 1
-- ==============================================